FROM node:20-alpine

WORKDIR /app

COPY package*.json ./

RUN npm set strict-ssl false \
    && npm config set registry="http://registry.npmjs.org/" \ 
    && npm install

COPY . .

RUN npm run build 

CMD ["/bin/sh", "-c", "npm run start "]
