export const activityCilaLists = [
    { value: "1 - Enleiramento", label: "1 - Enleiramento" },
    { value: "2 - Construção e reforma de cerca de arame, cercas vivas e outras", label: "2 - Construção e reforma de cerca de arame, cercas vivas e outras" },
    { value: "3 - Reforma de curral", label: "3 - Reforma de curral" },
    { value: "4 - Construção de tulhas e galpões", label: "4 - Construção de tulhas e galpões" },
    { value: "5 - Construção de bebedouros", label: "5 - Construção de bebedouros" },
    { value: "6 - Construção de cochos cobertos", label: "6 - Construção de cochos cobertos" },
    { value: "7 - Aquisição de animais (cria, recria e engorda)", label: "7 - Aquisição de animais (cria, recria e engorda)" },
    { value: "8 - Aquisição de aves, peixes e alevinos", label: "8 - Aquisição de aves, peixes e alevinos" },
    { value: "9 - Roço", label: "9 - Roço" },
    { value: "10 - Poda de árvores", label: "10 - Poda de árvores" },
    { value: "11 - Aração, adubação, correção de solo", label: "11 - Aração, adubação, correção de solo" },
    { value: "12 - Semeadura, tratos culturais", label: "12 - Semeadura, tratos culturais" },
    { value: "13 - Reforma de estábulo, aviários e apiários", label: "13 - Reforma de estábulo, aviários e apiários" },
    { value: "14 - Cobertura de casa, estábulos, currais e outros", label: "14 - Cobertura de casa, estábulos, currais e outros" },
    { value: "15 - Aquisição de equipamentos de irrigação, inseminação", label: "15 - Aquisição de equipamentos de irrigação, inseminação" },
    { value: "16 - Aquisição de veículos utilitários, tronco, balança, cochos móveis", label: "16 - Aquisição de veículos utilitários, tronco, balança, cochos móveis" },
    { value: "17 - Aquisição de arame liso e farpado", label: "17 - Aquisição de arame liso e farpado" },
    { value: "18 - Aquisição de kit de inseminação (doses de sêmen, nitrogênio, cortador, paletas, luvas, etc)", label: "18 - Aquisição de kit de inseminação (doses de sêmen, nitrogênio, cortador, paletas, luvas, etc)" },
    { value: "19 - Aquisição de ração, sal mineral, vacinas, medicamentos, vermífugos, etc", label: "19 - Aquisição de ração, sal mineral, vacinas, medicamentos, vermífugos, etc" },
    { value: "20 - Aquisição de aerador", label: "20 - Aquisição de aerador" },
    { value: "21 - Aquisição de freezer e câmara fria", label: "21 - Aquisição de freezer e câmara fria" },
    { value: "22 - Instalações elétricas", label: "22 - Instalações elétricas" },
    { value: "23 - Aquisição de redes, tarrafas e outros implementos de piscicultura", label: "23 - Aquisição de redes, tarrafas e outros implementos de piscicultura" },
    { value: "24 - Aquisição de gaiolas e balanças", label: "24 - Aquisição de gaiolas e balanças" },
    { value: "25 - Aquisição de insumos para apicultura (cera, caixa, EPI’s, etc)", label: "25 - Aquisição de insumos para apicultura (cera, caixa, EPI’s, etc)" },
    { value: "26 - Reformas de aprisco", label: "26 - Reformas de aprisco" },
    { value: "27 - Reforma de apiários", label: "27 - Reforma de apiários" },
    { value: "28 - Aquisição de incubadoras", label: "28 - Aquisição de incubadoras" },
    { value: "29 - Aquisição de insumos", label: "29 - Aquisição de insumos" },
    { value: "30 - Reforma de pocilgas", label: "30 - Reforma de pocilgas" },
    { value: "31 - Aquisição de calcário", label: "31 - Aquisição de calcário" },
    { value: "32 - Aquisição de semente", label: "32 - Aquisição de semente" },
    { value: "33 - Aquisição de defensivos agrícolas e herbicidas, outros insumos", label: "33 - Aquisição de defensivos agrícolas e herbicidas, outros insumos" },
    { value: "34 - Aquisição de mudas florestais e frutíferas", label: "34 - Aquisição de mudas florestais e frutíferas" },
    { value: "35 - Custeio agrícola e pecuário", label: "35 - Custeio agrícola e pecuário" },
    { value: "36 - Escritório Administrativo para prestação de serviços diversos", label: "36 - Escritório Administrativo para prestação de serviços diversos" },
    { value: "37 - Serviços de Cartografia e Topografia", label: "37 - Serviços de Cartografia e Topografia" },
    { value: "38 - Transporte intermunicipal de mudança doméstica (carga seca)", label: "38 - Transporte intermunicipal de mudança doméstica (carga seca)" },
    { value: "39 - Transporte intermunicipal de grãos (carga seca)", label: "39 - Transporte intermunicipal de grãos (carga seca)" },
    { value: "40 - Aquisição de equipamentos e veículos em geral", label: "40 - Aquisição de equipamentos e veículos em geral" },
    { value: "41 - Restauração e conservação de lugares e prédios históricos", label: "41 - Restauração e conservação de lugares e prédios históricos" },
    { value: "42 - Comércio varejista de artigos de caça, pesca e camping", label: "42 - Comércio varejista de artigos de caça, pesca e camping" },
    { value: "43 - Comércio varejista de medicamentos veterinários", label: "43 - Comércio varejista de medicamentos veterinários" },
    { value: "44 - Comercio varejista de artigos de armarinho e papelaria", label: "44 - Comercio varejista de artigos de armarinho e papelaria" },
    { value: "45 - Produção de ovos", label: "45 - Produção de ovos" },
    { value: "46 - Confecção de peças de vestuário, roupas íntimas e as confeccionadas sob medida", label: "46 - Confecção de peças de vestuário, roupas íntimas e as confeccionadas sob medida" },
    { value: "47 - Atividades paisagísticas – exceto com intervenção em corpo hídrico e área de APP", label: "47 - Atividades paisagísticas – exceto com intervenção em corpo hídrico e área de APP" },
    { value: "48 - Comércio varejista de cosméticos, produtos de perfumaria e de higiene pessoa", label: "48 - Comércio varejista de cosméticos, produtos de perfumaria e de higiene pessoa" },
    { value: "49 - Comércio varejista de bebidas", label: "49 - Comércio varejista de bebidas" },
    { value: "50 - Comércio varejista de mercadorias em geral", label: "50 - Comércio varejista de mercadorias em geral" },
    { value: "51 - Academia para prática de exercício físico em geral", label: "51 - Academia para prática de exercício físico em geral" },
    { value: "52 - Implantação de alambrado para área de prática de esporte", label: "52 - Implantação de alambrado para área de prática de esporte" },
    { value: "53 - Comércio varejista ou atacadista de embalagens (casa de embalagens)", label: "53 - Comércio varejista ou atacadista de embalagens (casa de embalagens)" },
    { value: "54 - Salão de Beleza", label: "54 - Salão de Beleza" },
  ];
  