export const centralized = [
  { value: "Cabixi", label: "Cabixi" },
  { value: "Cacaulândia", label: "Cacaulândia" },
  { value: "Castanheiras", label: "Castanheiras" },
  { value: "Cerejeiras", label: "Cerejeiras" },
  { value: "Chupinguaia", label: "Chupinguaia" },
  { value: "Corumbiara", label: "Corumbiara" },
  { value: "Costa Marques", label: "Costa Marques" },
  { value: "Cujubim", label: "Cujubim" },
  { value: "Governador Jorge Teixeira", label: "Governador Jorge Teixeira" },
  { value: "Ministro Andreazza", label: "Ministro Andreazza" },
  { value: "Nova União", label: "Nova União" },
  { value: "Novo Horizonte do Oeste", label: "Novo Horizonte do Oeste" },
  { value: "Parecis", label: "Parecis" },
  { value: "Pimenteiras do Oeste", label: "Pimenteiras do Oeste" },
  { value: "Presidente Médici", label: "Presidente Médici" },
  { value: "Rio Crespo", label: "Rio Crespo" },
  { value: "Santa Luzia do Oeste", label: "Santa Luzia do Oeste" },
  { value: "São Felipe do Oeste", label: "São Felipe do Oeste" },
  { value: "São Francisco do Guaporé", label: "São Francisco do Guaporé" },
  { value: "Seringueiras", label: "Seringueiras" },
  { value: "Teixeirópolis", label: "Teixeirópolis" },
];
